### ISSUE TITLE
Arm stabiliser not adjusting in size

### ISSUE THREAD

**Issue by steinbeck** [hugokernel/OpenSCAD_ServoArms#2]
First of all, thanks for sharing this. Very useful!
Small bug: when I make the head diameter smaller, the stabilizer does not change in size and at one point does not touch the head anymore :)

**Comment by hugokernel** [comment]
Hi, Could you provide a running example please ?

**Comment by steinbeck** [comment]
Yes, sorry. Using exactly the code in your repo, just set the head external diameter to 3mm in the FUTABA_3F_SPLINE and compile. 
[servoarm.scad.zip](https://github.com/hugokernel/OpenSCAD_ServoArms/files/6244693/servoarm.scad.zip)

**Comment by hugokernel** [comment]
Running example:

```OpenScad
UNKNOW_SERVO_SPLINE = [
    [3, 4, 1.1, 2.5],
    [25, 0.3, 0.7, 0.1]
];

servo_arm(UNKNOW_SERVO_SPLINE, [length, count]);
```
