### ISSUE TITLE
no issue

### ISSUE THREAD

**Issue by FOSSBOSS** [hugokernel/OpenSCAD_ServoArms#6]
This is awesome, thanks so much!

**Comment by hugokernel** [comment]
I like this kind of issue !

**Comment by FOSSBOSS** [comment]
I have a feature request:
Please make a connector to attach to the shaft of potentiometers, as to replace knobs with a servo attachment. 
( tried making it, but I'm not good at OpenScad yet. )
![trying](https://github.com/hugokernel/OpenSCAD_ServoArms/assets/12141764/26474a2a-f474-4186-b47b-dc9779bdf259)

**Comment by hugokernel** [comment]
This is outside the scope of this project.

This repository is specifically designed for parametric servo arm generation.
